### PR TITLE
Add a doctype declaration to generated output

### PR DESCRIPTION
**Pull request by mthmulders**
When using a non-standard Reveal theme, I noticed Chrome loaded the _user agent stylesheet_. In another presentation, that uses the same theme, but that does *not* use `kc-serve`, this was not the case. This was caused by the fact that the latter presentation had  a `<doctype>` declaration at the top of the HTML file. `kc-serve` does not genererate that.

This PR adds the `<doctype>` declaration to the generated HTML.

### CODE REVIEW

**Review by riezebosch — COMMENTED** [review]
Isn't this the more appropriate location to add that: https://github.com/kc/kc-serve/blob/master/src/template/Index.tsx

**Comment by mthmulders** [comment]
Well, you're absolutely right. I tried that, but the first time I couldn't get it to work, so I figured this as a work-around. I've tried it again, this time it works. Don't know why it didn't work out the first time...

**Comment by riezebosch** [comment]
The quotes and concatenation shouldn't be necessary (since it already is a JSX style template).

**Comment by mthmulders** [comment]
> The quotes and concatenation shouldn't be necessary (since it already is a JSX style template).

Well, in fact it is:
* If you'd omit them, the `render()` method would return more than one JSX element, which does not work.
* Wrapping the `<!doctype html`> together with the `<html>` in an array doesn't work either. AFAIK, only the React implementation of JSX supports this.
* There is no [typed-html](https://github.com/nicojs/typed-html) support for doctype, since it is not an element but a declaration.

**Comment by riezebosch** [comment]
Added a test for it: https://github.com/kc/kc-serve/commit/84e041ec9e869d0cc4a646a0d64224520f64539e

**Pull request merged**
